---
# handlers file for ansible-role-docker-swarm

- name: start docker
  service: name=docker state=started

- name: stop docker
  service: name=docker state=stopped

- name: restart docker
  service: name=docker state=restarted

- name: reload systemd
  command: systemctl daemon-reload
